# configs/default.yaml
seed: 42
n_iters: 3
num_episodes: 10
steps_per_episode: 30
env_name: deep-sea-treasure-v0
experience_multiplier: 100
render_mode: None
plotting: False


# TODO:
# docstrings: include references
# Run with different time horizons